# To execute this script we need to perform three things
# 1) installing python related libraries called boto3 and botocore pip3.9 install botocore boto3
# 2) Need to create the user using IAM
# 3) Need to configure the access key which was created as part of user at IAM level and have to be configured in the below like aws configure

- name: create ec2 and r53 records
  hosts: localhost
  vars:
    zone: somustack.online
    instances:
    - db
    - frontend
    - backend
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      instance_type: t2.micro
      name: "{{ item }}"
      security_group: allow-all #replace with you AWS values
      image_id: ami-090252cbe067a9e58
      tags:
        Name: "{{ item }}"
      loop: "{{ instances }}"
      register: ec2_instances_info
  
  - name: print output
    ansible.builtin.debug:
      msg: "The Output : {{ ec2_instances_info }}"


  #- name: create Route53 records
   # amazon.aws.route53:
