- name: Create EC2 Servers and Update Rout53 Records
  hosts: localhost
  vars:
    zone: somustack.online
    instances:
    - db
    - backend
    - frontend
  tasks:
  - name: Create EC2 instances
    amazon.aws.ec2_instance:
      instance_type: t2.micro
      name: "{{ item }}"
      security_group: allow-all # this is what i created under security groups
      image_id: ami-090252cbe067a9e58
      tags:
        Name: "{{ item }}"
    loop:
      name: "{{ instances }}"    
    register: ec2_instances_info
  
  - name: Print Output
    ansible.builtin.debug:
      msg: "Output:" {{ec2_instances_info}}
  
  - name: Create R53 records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: " {{ item }}.{{zone}}"
      type: A
      value: "{{ item.instances.private_ip_address }}"
      overwrite: true
      ttl: 1
    loop: "{{ ec2_instances_info.results }}"