- name: create ec2 and r53 records
  hosts: localhost
  vars:
    zone: somustack.online
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      instance_type: t2.micro
      name: "{{ item }}"
      security_group: allow-all #replace with you AWS values
      image_id: ami-090252cbe067a9e58
      tags:
        Name: "{{ item }}"
    loop:
    - db
    - backend
    - frontend
    register: ec2_instances_info
  
  - name: print output
    ansible.builtin.debug:
      msg: "Output : {{ ec2_instances_info }}"